### ISSUE TITLE
lab2/exercise14.py

### ISSUE THREAD

**Issue by kolganovn** [python-practice-b02-927/Kuhmistrov#16]
Какие-то проблемы с углами, звёзды рисуются неправильно.

**Comment by WebKooH** [comment]
Случайно залил не ту версию кода. Исправлено.

**Comment by kolganovn** [comment]
Звезды с четным числом углов недорисовываются. Правда в задании было 5 и 11

**Comment by WebKooH** [comment]
> Звезды с четным числом углов недорисовываются. Правда в задании было 5 и 11

Думаю, звезды с четным кол-вом вершин и не подразумеваются в этом задании. Во всяком случае, не отрывая пера их нарисовать невозможно, что несложно доказать.
